# fly.toml app configuration file generated for growatt-scrapping on 2024-11-12T17:33:14-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'growatt-scrapping'
primary_region = 'mia'

[build]
dockerfile = ".docker/Dockerfile.production"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "off"
auto_start_machines = true
min_machines_running = 1
processes = ['app']
[http_service.http_options]
idle_timeout = 600

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
