# Instal bun image
FROM oven/bun:latest

# Bun app lives here
WORKDIR /app

# Set production environment
ENV NODE_ENV="development"

# Install dependencies for playwright
RUN bunx -y playwright install --with-deps webkit

# Install node modules
COPY bun.lockb package.json ./
RUN bun install --ci

# Copy application code
COPY . .

# Start the server by default, this can be overwritten at runtime
EXPOSE 3000
CMD [ "bun", "run", "start" ]
