# Instal bun image
FROM oven/bun:latest

# Bun app lives here
WORKDIR /app

# Set production environment
ENV NODE_ENV="development"

# Install node modules
COPY bun.lockb package.json ./
RUN bun install --ci

# Copy application code
COPY . .

# Start the server by default, this can be overwritten at runtime
EXPOSE 3000
CMD [ "bun", "--watch", "src/index.ts" ]
